### ISSUE TITLE
 Python 3 Compatibility

### ISSUE THREAD

**Issue by JanKoopm** [tjjfvi/OctoPrint-BetterHeaterTimeout#15]
Please add Python 3 Compatibility as outlined [here](https://docs.octoprint.org/en/master/plugins/python3_migration.html).

**Comment by tjjfvi** [comment]
Please go to [any](https://github.com/tjjfvi/OctoPrint-BetterHeaterTimeout/issues/7) [other](https://github.com/tjjfvi/OctoPrint-BetterHeaterTimeout/issues/10)  [existing](https://github.com/tjjfvi/OctoPrint-BetterHeaterTimeout/issues/11) [compatibility](https://github.com/tjjfvi/OctoPrint-BetterHeaterTimeout/issues/12) [issue](https://github.com/tjjfvi/OctoPrint-BetterHeaterTimeout/issues/13) and give your support there, rather than posting another issue.
